### ISSUE TITLE
App open source

### ISSUE THREAD

**Issue by Jiack214** [irplus-remote/irplus-remote.github.io#1]
Hi, is it in your plans to make the android app open source someday?
Thanks

**Comment by gemmcomitsp** [comment]
I just forked from someone else.

His app is closed. I've been trying to change the app to use BT Serial
instead of the buit in IR blaster.

No such luck. The code is intense and deep.

If I'm able to get the app changed, then yes. I'll make my version open
source.

**Comment by irplus-remote** [comment]
Its kinda thought as my own project which i am in full control and i have no plans to open it yet. 

One day - when i got bored of developing it i will make it available. If you have questions, ideas or suggestions (features) I'm happy to hear feedback.

**Comment by irplus-remote** [comment]
About the BT serial. If you can provide a simple api on how to send raw IR commands to your BT device i can try to add support if its not too complex
